#!/bin/zsh

# MODEL=qwen3.6:35b-a3b-nvfp4
# MODEL=qwen3.6:27b-mlx
MODEL=gemma4:e4b-mlx

OLLAMA_CONTEXT_LENGTH=256000 OLLAMA_FLASH_ATTENTION=1 OLLAMA_NUM_PARALLEL=1 OLLAMA_KV_CACHE_TYPE=q8_0 ollama launch claude --model ${MODEL}
